### PR TITLE
fix:footer on Desktop Safari #129

### PR DESCRIPTION
**Pull request by chiragbadhe**
Fixed the footer alignment issue on Safari by adding width="full" to the Grid component. The footer now displays correctly on all browsers.

### CODE REVIEW

**Comment by chiragbadhe** [comment]
@MantisClone can you please review it once

**Review by MantisClone — APPROVED** [review]

**Comment by MantisClone** [comment]
Hello @chiragbadhe. The BanklessDAO Website project is offering a 1000 BANK bounty for this task: [dw-185](https://app.dework.xyz/banklessdao-1/website-project-2?taskId=2fbd5824-ca1c-4be8-aad7-8421807aef2c). However, I cannot find your DeWork profile and therefore cannot assign the bounty payout to your Ethereum address. Please send me a link to your DeWork profile so that I can make sure you get paid for this work.

**Comment by chiragbadhe** [comment]
Hi @MantisClone, Here's my dework profile https://app.dework.xyz/profile/ch1rag.eth

**Comment by MantisClone** [comment]
Sorry for the late reply @chiragbadhe. Unfortunately, DeWork doesn't let me directly assign you to [dw-185](https://app.dework.xyz/banklessdao-1/website-project-2?taskId=2fbd5824-ca1c-4be8-aad7-8421807aef2c). Instead, can you please do one of the following:

* Accept my Discord friend request so I can send you a DeWork invite code.
* Submit an application to work on [dw-185](https://app.dework.xyz/banklessdao-1/website-project-2?taskId=2fbd5824-ca1c-4be8-aad7-8421807aef2c) so I can accept your application.

Finally, once you've been assigned the task, can you please click "Submit Work" and enter _this_ PR link as the submission? After that, I'll be able to accept the submission and the task will be marked done and the bounty can be paid out.

**Pull request merged**
