### PR TITLE
feat: Bankless Notion CMS for departments, guilds and projects

### PR DESCRIPTION
**Pull request by didierkrux**
Fixes [dw-210](https://app.dework.xyz/banklessdao-1/website-project-2?taskId=90aa260c-bd81-402f-a203-3b59ce1306a2)

### CODE REVIEW

**Comment by MantisClone** [comment]
Thanks for the contribution!  I'll take a look.

**Comment by MantisClone** [comment]
@didierkrux I think we need to remove the old images, now that we've added new copies.

Also, will the script duplicate the images each time it runs?  Or is the hash in the image filename deterministic?

**Review by MantisClone — COMMENTED** [review]
Looks really good. My only comment is that I think we need to delete the old images that are no longer used.

**Comment by didierkrux** [comment]
> @didierkrux I think we need to remove the old images, now that we've added new copies.
> 
> Also, will the script duplicate the images each time it runs? Or is the hash in the image filename deterministic?

Good point, I'll remove the old images.

The script doesn't duplicate the images unless that image has been updated (the hash is deterministic).

FYI I've created a third version here https://github.com/BanklessDAO/bankless-website/pull/256 based on your PR cloudflare PR this time https://github.com/BanklessDAO/bankless-website/pull/232 so I'm going to close this one an finish there.

**Pull request closed without merging**
