### PR TITLE
feat: Bankless Notion CMS for departments, guilds and projects

### PR DESCRIPTION
**Pull request by didierkrux**
Fixes [dw-210](https://app.dework.xyz/banklessdao-1/website-project-2?taskId=90aa260c-bd81-402f-a203-3b59ce1306a2)

### CODE REVIEW

**Comment by MantisClone** [comment]
Hey @didierkrux Can you please submit your PR to the DeWork task? [dw-210](https://app.dework.xyz/banklessdao-1/website-project-2?taskId=90aa260c-bd81-402f-a203-3b59ce1306a2)

**Comment by MantisClone** [comment]
I'm not sure why it's complaining about merge conflicts.
image

**Review by MantisClone — APPROVED** [review]

**Comment by didierkrux** [comment]
> I'm not sure why it's complaining about merge conflicts. image

Not sure either ... all these guilds and project files get deleted anyway ...

Do I need to solved these issues?

**Comment by MantisClone** [comment]
I can take a look later. I don't have time now.

**Comment by didierkrux** [comment]
> I can take a look later. I don't have time now.

I've resolved the conflicts, let's see if the preview link deploys correctly ...

**Comment by MantisClone** [comment]
Question: Is the import-notion.js script automated?  Or do we still need to automate it?

In this case, I mean "automated" like the marketing department changes the Notion, and the website automatically redeploys without me or @BOBOtoTHEmoon having to do anything.

**Comment by didierkrux** [comment]
> Question: Is the import-notion.js script automated? Or do we still need to automate it?
> 
> In this case, I mean "automated" like the marketing department changes the Notion, and the website automatically redeploys without me or @BOBOtoTHEmoon having to do anything.

You have to run the manually locally. It's better so you can review the changes before committing them (more secure).

**Comment by MantisClone** [comment]
I bet we could put it in a GitHub action and run it periodically, and if there's a change, it'll automatically create a PR to be reviewed.

**Review by MantisClone — APPROVED** [review]

**Pull request merged**
