### PR TITLE
/read - page updates

### PR DESCRIPTION
**Pull request by activate-glacier-instinct**

### CODE REVIEW

**Comment by CompositeFellow** [comment]
@activate-glacier-instinct The coin graphics disappear on the mobile version, but they are there in the figma.  If this is on purpose let me know.  I think if we fix this, then this one is good to go

**Comment by CompositeFellow** [comment]
@activate-glacier-instinct sorry one more, the top 2 links don't work for me, the medium and mirror article.

**Comment by activate-glacier-instinct** [comment]
> @activate-glacier-instinct sorry one more, the top 2 links don't work for me, the medium and mirror article.
> @activate-glacier-instinct The coin graphics disappear on the mobile version, but they are there in the figma. If this is on purpose let me know. I think if we fix this, then this one is good to go

@CompositeFellow 

Thanks for the review, both of these should be fixed now. 

Screenshot for the token below :point_down: 

localhost_3000_read

**Comment by activate-glacier-instinct** [comment]
F
Screenshot from 2022-05-09 01-43-27
ixes the rug links to the stacked on mobile

**Comment by CompositeFellow** [comment]
Looks good.  I think we are good here.  I don't think I have access to add a review on this repo

**Review by CompositeFellow — APPROVED** [review]
Nevermind, im dumb.  Approved.

**Review by CompositeFellow — APPROVED** [review]

**Review by singularityhacker — APPROVED** [review]
👍

**Pull request merged**
