### PR TITLE
mobile nav dropdown

### PR DESCRIPTION
**Pull request by Yembot31013**

### CODE REVIEW

**Review by MantisClone — CHANGES_REQUESTED** [review]
Thank you for your contribution!  It's close to being done, but I have a few change requests:

1. I don't like that the menu items are compact on medium-width screens. I think they should be spaced out like the menu items on small-width screens.
Spaced out :+1: 
Screenshot from 2023-05-28 08-22-29
Compact :-1: 
Screenshot from 2023-05-28 08-22-41
2. I don't like how the top-level menu item is "Discover" on small and medium-width screens. I also don't like how "ABOUT US" is a sub-menu item under "Discover" on small and medium-width screens. I want the top-level menu item to be "About Us" on all screen sizes.
image
3. I don't like that the sub-menu items ("GOVERNANCE", "PROJECTS", etc.) are all-capitalized. I want them to be capitalized like the top-level menu items (for example: "Work With Us", "Read")
4. I don't like how tapping the word "Discover" on mobile only highlights the word and fails to reveal the sub-menu items. Only tapping the down arrow :arrow_down:  next to Discover reveals the sub-menu items. I want to be able to tap the word, not just the arrow.
Screenshot_20230528-082939
5. I don't like how tapping the down arrow a 2nd time does not hide the sub-menu items. I want to be able to hide the sub-menu items by tapping the word or down arrow :arrow_down: a 2nd time.

**Comment by Yembot31013** [comment]
I chose to label the main menu as "Discover" instead of "About Us" because having "About Us" as the main menu item would make it inaccessible on small and medium-sized screens, as it already has its own page. If we made it a link, the drop-down menu would not function properly. Therefore, I suggest renaming the main menu to something other than "Discover" or "About Us."

If having "ABOUT US" as a sub-menu item under "Discover" is not to your liking, then I may need to move "About Us" outside the sub-menu items. However, replacing "Discover" with it would not be a good idea, as it would interfere with the redirection (link) of the About Us page.

The current mobile behavior where tapping the word "Discover" only highlights it without revealing the sub-menu items is not what I implemented. I made it so that tapping both the word and the arrow would reveal the sub-menu items. However, I will review this behavior again to ensure it is functioning properly.

Thank you.

**Comment by Yembot31013** [comment]
> Thank you for your contribution! It's close to being done, but I have a few change requests:
> 
> 1. I don't like that the menu items are compact on medium-width screens. I think they should be spaced out like the menu items on small-width screens.
>    Spaced out 👍
>    Screenshot from 2023-05-28 08-22-29
>    Compact 👎
>    Screenshot from 2023-05-28 08-22-41
> 2. I don't like how the top-level menu item is "Discover" on small and medium-width screens. I also don't like how "ABOUT US" is a sub-menu item under "Discover" on small and medium-width screens. I want the top-level menu item to be "About Us" on all screen sizes.
>    image
> 3. I don't like that the sub-menu items ("GOVERNANCE", "PROJECTS", etc.) are all-capitalized. I want them to be capitalized like the top-level menu items (for example: "Work With Us", "Read")
> 4. I don't like how tapping the word "Discover" on mobile only highlights the word and fails to reveal the sub-menu items. Only tapping the down arrow ⬇️  next to Discover reveals the sub-menu items. I want to be able to tap the word, not just the arrow.
>    Screenshot_20230528-082939
> 5. I don't like how tapping the down arrow a 2nd time does not hide the sub-menu items. I want to be able to hide the sub-menu items by tapping the word or down arrow ⬇️ a 2nd time.

I chose to label the main menu as "Discover" instead of "About Us" because having "About Us" as the main menu item would make it inaccessible on small and medium-sized screens, as it already has its own page. If we made it a link, the drop-down menu would not function properly. Therefore, I suggest renaming the main menu to something other than "Discover" or "About Us."

If having "ABOUT US" as a sub-menu item under "Discover" is not to your liking, then I may need to move "About Us" outside the sub-menu items. However, replacing "Discover" with it would not be a good idea, as it would interfere with the redirection (link) of the About Us page.

The current mobile behavior where tapping the word "Discover" only highlights it without revealing the sub-menu items is not what I implemented. I made it so that tapping both the word and the arrow would reveal the sub-menu items. However, I will review this behavior again to ensure it is functioning properly.

Thank you.

**Comment by MantisClone** [comment]
> I chose to label the main menu as "Discover" instead of "About Us" because having "About Us" as the main menu item would make it inaccessible on small and medium-sized screens, as it already has its own page. If we made it a link, the drop-down menu would not function properly. 

Thank you for explaining @Yembot31013. Now that I understand the issue, I have a new change request: Please make the menu flat on mobile - where all pages are top-level menu items but indent and use a slightly smaller font size for the sub-menu items. The order should be like so:

```
Home
About Us
  Governance
  Guilds
  Projects
  Community Calls
  Media Nodes
Work With Us
Read
Invest
Listen
New Members Start
```

Given the increased number of top-level menu items, please reverse my point (2) and make the menu items compact on small and medium-sized screens. 

> The current mobile behavior where tapping the word "Discover" only highlights it without revealing the sub-menu items is not what I implemented. I made it so that tapping both the word and the arrow would reveal the sub-menu items. However, I will review this behavior again to ensure it is functioning properly.

On second look, I realize that I was wrong about this. Tapping the word "Discover" DOES reveal the sub-menu items :facepalm:  I still don't like that it highlights so easily, but luckily, after the menu is flattened, this issue is eliminated.

**Comment by Yembot31013** [comment]
Regarding the task, I have completed it. However, for the highlighting issue, should I set the cursor-pointer to none?

**Comment by BOBOtoTHEmoon** [comment]
@Yembot31013 use smaller font for the submenu

**Review by MantisClone — CHANGES_REQUESTED** [review]
1. Can you please make the sub-menu titles the same case as the main menu titles?
GOVERNANCE -> Governance
GUILDS -> Guilds
PROJECTS -> Project
COMMUNITY CALLS -> Community Calls
MEDIA NODES -> Media Nodes

2. On mobile the flat menu looks good :+1: But can you please make the menu items appear more compact, closer together?
image


3. On the desktop, the menu items appear too close together. Can you please make the menu items look less compact, further apart, like they used to be?
PR: 
image
Desired:
image

**Comment by Yembot31013** [comment]
> 1. Can you please make the sub-menu titles the same case as the main menu titles?
>    GOVERNANCE -> Governance
>    GUILDS -> Guilds
>    PROJECTS -> Project
>    COMMUNITY CALLS -> Community Calls
>    MEDIA NODES -> Media Nodes
> 2. On mobile the flat menu looks good 👍 But can you please make the menu items appear more compact, closer together?
>    image
> 3. On the desktop, the menu items appear too close together. Can you please make the menu items look less compact, further apart, like they used to be?
>    PR:
>    image
>    Desired:
>    image

@MantisClone @BOBOtoTHEmoon Done! please review it

**Review by MantisClone — APPROVED** [review]
Looks good to me!

**Review by MantisClone — APPROVED** [review]
Looks good to me! Thanks!

**Pull request merged**
