### PR TITLE
fix(dw-162): hand video autoloop on Safari

### LINKED ISSUE #61: Autoloop for bDAO Hand video not running on Safari
The video of the bDAO hand doesn’t auto loop on Safari, iPhone.

[Read more about this task and rewards on Dework.xyz](https://app.dework.xyz/banklessdao-1/website-project-2?taskId=4f5accae-b3ac-4030-901a-db15b6ef289b)

### PR DESCRIPTION
**Pull request by BOBOtoTHEmoon**
Fixes [dw-162](https://app.dework.xyz/banklessdao-1/website-project-2?taskId=4f5accae-b3ac-4030-901a-db15b6ef289b)
Fixes #61 

I'm making use of *createRef()* method to create a reference to the video element, and then using the *play()* method to start the video when the *onCanPlay* event is fired. This allows the video to start playing automatically, while also addressing the limitations of the *autoplay* attribute on Safari.

Also, I added a new method *handleEnded* that will be called when the video ends, it will reset the *currentTime* to 0 and call the play method again so the video can loop.

### CODE REVIEW

**Review by MantisClone — CHANGES_REQUESTED** [review]
Thanks @BOBOtoTHEmoon. Unfortunately, this PR fails to build so it cannot be merged.

Here's the build log from Vercel:
```
Cloning github.com/BanklessDAO/bankless-website (Branch: dw-162, Commit: 0ce9cbb)
--
12:40:28.368 | Cloning completed: 6.830s
12:40:28.557 | Restored build cache
12:40:28.599 | Running "vercel build"
12:40:29.063 | Vercel CLI 28.12.7
12:40:29.372 | Installing dependencies...
12:40:29.669 | yarn install v1.22.17
12:40:29.738 | [1/4] Resolving packages...
12:40:30.078 | success Already up-to-date.
12:40:30.088 | $ husky install
12:40:30.165 | husky - Git hooks installed
12:40:30.168 | Done in 0.50s.
12:40:30.186 | Detected Next.js version: 12.1.0
12:40:30.188 | Running "yarn run build"
12:40:30.449 | yarn run v1.22.17
12:40:30.475 | $ next build
12:40:31.121 | Browserslist: caniuse-lite is outdated. Please run:
12:40:31.122 | npx browserslist@latest --update-db
12:40:31.122 | Why you should do it regularly: https://github.com/browserslist/browserslist#browsers-data-updating
12:40:31.140 | info  - Checking validity of types...
12:40:36.628 | Failed to compile.
12:40:36.628 |  
12:40:36.629 | ./components/home/section1.tsx:15:7
12:40:36.629 | Type error: Object is of type 'unknown'.
12:40:36.629 |  
12:40:36.629 |   13 \|   handlePlay = () => {
12:40:36.629 |   14 \|     if (this.videoRef.current) {
12:40:36.629 | > 15 \|       this.videoRef.current.play();
12:40:36.629 |      \|       ^
12:40:36.629 |   16 \|     }
12:40:36.629 |   17 \|   }
12:40:36.630 |   18 \|
12:40:36.656 | error Command failed with exit code 1.
12:40:36.656 | info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
12:40:36.676 | Error: Command "yarn run build" exited with 1
```

**Comment by BOBOtoTHEmoon** [comment]
@MantisClone , what do i do if this PR fails to build

**Review by MantisClone — CHANGES_REQUESTED** [review]
This PR still fails to build. I'm not sure how to fix it.

Build log:
```
Cloning github.com/BanklessDAO/bankless-website (Branch: dw-162, Commit: 85cd75b)
Cloning completed: 8.841s
Restored build cache
Running "vercel build"
Vercel CLI 28.13.0
Installing dependencies...
yarn install v1.22.17
[1/4] Resolving packages...
[2/4] Fetching packages...
[3/4] Linking dependencies...
warning " > cypress-image-snapshot@4.0.1" has incorrect peer dependency "cypress@^4.5.0".
warning "cypress-image-snapshot > jest-image-snapshot@4.2.0" has incorrect peer dependency "jest@>=20 <=26".
warning " > slick-carousel@1.8.1" has unmet peer dependency "jquery@>=1.8.0".
[4/4] Building fresh packages...
$ husky install
husky - Git hooks installed
Done in 60.00s.
Detected Next.js version: 12.1.0
Running "yarn run build"
yarn run v1.22.17
$ next build
Browserslist: caniuse-lite is outdated. Please run:
  npx browserslist@latest --update-db
  Why you should do it regularly: https://github.com/browserslist/browserslist#browsers-data-updating
info  - Checking validity of types...
Failed to compile.
./components/home/section1.tsx:15:7
Type error: Object is of type 'unknown'.
  13 |   componentDidMount() {
  14 |     if (this.videoRef.current) {
> 15 |       this.videoRef.current.play();
     |       ^
  16 |     }
  17 |   }
  18 | 
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
Error: Command "yarn run build" exited with 1

```

**Comment by MantisClone** [comment]
Superseded by #137

**Pull request closed without merging**
