### PR TITLE
/about-us - improvements

### PR DESCRIPTION
**Pull request by activate-glacier-instinct**

### CODE REVIEW

**Comment by CompositeFellow** [comment]
@activate-glacier-instinct looks good to me.  Two small things.  
1) in the figma there is the red gradient svg behind the animation.  Are we scrapping that?  I assume it doesn't show up if its behind the animation.  Animation looks awesome btw

2)  I'm getting a strange bug.  If I middle click any of the links they don't work.  If I click normally they work fine.  

Everything else looks great.  I think the above shouldn't prevent the above from being pushed.

**Review by CompositeFellow — APPROVED** [review]
Two small bugs described above, but I think this is safe to merge

**Comment by activate-glacier-instinct** [comment]
> 2\. iddle click any of the link

Hmmm the middle click might be target.

Thanks for the review! I'll check that out.

FYI trying to sort out the left/right content section - responsiveness been a bit annoying here.

**Comment by activate-glacier-instinct** [comment]
Summarising the leftover tasks: 

```
- header
        - gradient behind the main graphic
        - rotate the icons 360deg
        - nav should stay on one line
    - main text
        - padding
        - images
        - responsiveness
    - improve circle element images
    - our vision header
        - trim the title
        - add the rest of the title to the main body
    - our values
        - review the carousel
    - add video
    - remove the red circles 
    - update images
    - links overall
```

**Comment by activate-glacier-instinct** [comment]
Done tonight 

```
- [x] header
    - [x] gradient behind the main graphic
    - rotate the icons 360deg
    - [x] nav should stay on one line
- [x] remove the red circles 
- [x] links overall
- [x] our vision header
    - trim the title
    - add the rest of the title to the main body
```

Left to do:

```
- main text
    - padding
    - images
    - responsiveness
- improve circle element images
- our values
    - review the carousel
- add video
- update images
```

**Comment by activate-glacier-instinct** [comment]
@CompositeFellow Ready for a review once the build is done

**Review by CompositeFellow — APPROVED** [review]

**Pull request merged**
